name: Cross Compile to AArch64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: uraimo/run-on-arch-action@v2
      name: Build
      id: build
      with:
        arch: aarch64
        distro: ubuntu_latest
        setup: |
          mkdir -p "${PWD}/artifacts"
        dockerRunArgs: |
          --volume "${PWD}/artifacts:/artifacts"
        env: | # YAML, but pipe character is necessary
          artifact_name: pocketfft-aarch64
        shell: /bin/bash
        run: |
          apt-get -q update
          apt-get install -y -q clang libc++-dev libc++abi-dev
          clang++ raytracing.github.io/src/InOneWeekend/main.cc -S -O3 -I raytracing.github.io/src/common -o rt1.s
          clang++ raytracing.github.io/src/TheNextWeek/main.cc -S -O3 -I raytracing.github.io/src/common -o rt2.s
          cp rt1.s /artifacts
          cp rt2.s /artifacts
#     - name: Show artifacts
#       run: |
#         ls -al "${PWD}/artifacts"
    - uses: actions/upload-artifact@v3
      with:
        name: Assembly
        path: ./artifacts/*.s